ccomptes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from flask_mongoengine import MongoEngine

db = MongoEngine()


class Report(db.Document):
    id = db.StringField(primary_key=True)
    juridiction = db.StringField()
    types = db.ListField(db.StringField())
    publication = db.DateTimeField()
    subject = db.StringField()
    topics = db.ListField(db.StringField())
    tags = db.ListField(db.StringField())
    content = db.StringField()
    short_content = db.StringField()

    def __unicode__(self):
        return self.subject

ccomptes/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from os.path import exists, join


class DefaultConfig(object):
    MONGODB_DB = 'ccomptes'
    SECRET_KEY = 'no-secret-this-is-open'
    MAIL_DEFAULT_SENDER = 'ccomptes@locahost'
    ANON_ALERT_MAIL = 'ccomptes.alert@locahost'


def create_app(config=None):
    from flask import Flask

    from ccomptes import views, api
    from ccomptes.assets import assets
    from ccomptes.models import db
    from ccomptes.search import es

    app = Flask('ccomptes')

    app.config.from_object(DefaultConfig)
    app.config.from_envvar('CCOMPTES_CONFIG', silent=True)

    custom_settings = join(os.getcwd(), 'ccomptes.cfg')
    if exists(custom_settings):
        app.config.from_pyfile(custom_settings)

    if config:
        app.config.from_object(config)

    # Optionnal Sentry support
    if 'SENTRY_DSN' in app.config:
        from raven.contrib.flask import Sentry
        Sentry(app)

    db.init_app(app)
    es.init_app(app)
    assets.init_app(app)
    views.init_app(app)
    api.init_app(app)

    return app


if __name__ == '__main__':
    app = create_app()
    app.run()

ccomptes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import cStringIO as StringIO
import re

from datetime import datetime

from urlparse import urlsplit, urlunsplit

from flask import Blueprint, abort, render_template, url_for, request, flash, Response, redirect
from flask_mail import Attachment, Mail
from flask_wtf import FlaskForm
from jinja2 import Markup
from werkzeug import url_decode, url_encode
from wtforms import TextField, ValidationError

from ccomptes import csvcustom
from ccomptes.models import Report
from ccomptes.search import search_reports, home_data

DEFAULT_PAGE_SIZE = 20

RE_URL = re.compile(r'https?://')


site = Blueprint('site', __name__)
mail = Mail()


@site.app_template_global(name='static')
def static_global(filename):
    return url_for('static', filename=filename)


@site.app_template_global()
@site.app_template_filter()
def url_rewrite(url=None, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key, value in kwargs.items():
        params.setlist(key, value if isinstance(value, (list, tuple)) else [value])
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
@site.app_template_filter()
def url_add(url=None, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key, value in kwargs.items():
        if value not in params.getlist(key):
            params.add(key, value)
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
@site.app_template_filter()
def url_del(url=None, *args, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(url or request.url)
    params = url_decode(query)
    for key in args:
        params.poplist(key)
    for key, value in kwargs.items():
        lst = params.poplist(key)
        if value in lst:
            lst.remove(value)
        params.setlist(key, lst)
    return Markup(urlunsplit((scheme, netloc, path, url_encode(params), fragments)))


@site.app_template_global()
def in_url(*args, **kwargs):
    scheme, netloc, path, query, fragments = urlsplit(request.url)
    params = url_decode(query)
    return (
        all(arg in params for arg in args)
        and
        all(key in params and params[key] == value for key, value in kwargs.items())
    )


@site.app_template_global()
@site.app_template_filter()
def treeize(topics, sep='/'):
    tree = {}
    for topic in topics:
        parts = topic.split(sep)
        if len(parts) == 1:
            tree[topic] = tree.get(topic, [])
        elif len(parts) == 2:
            if not parts[0] in tree:
                tree[parts[0]] = []
            tree[parts[0]].append(parts[1])
    return [(k, v) for k, v in sorted(tree.items())]


@site.app_template_global()
@site.app_template_filter()
def treeize_facet(topics, sep='/'):
    tree = {}
    for topic, count, active in topics:
        parts = topic.split(sep)
        if len(parts) == 1:
            tree[topic] = {
                'count': count,
                'active': active,
                'subtopics': tree.get(topic, {}).get('subtopics', [])
            }
        elif len(parts) == 2:
            if not parts[0] in tree:
                tree[parts[0]] = {
                    'count': count,
                    'active': active,
                    'subtopics': []
                }
            tree[parts[0]]['subtopics'].append((parts[1], count, active))
    return [
        (t, tree[t]['count'], tree[t]['active'], tree[t]['subtopics'])
        for t in sorted(tree, key=lambda k: tree[k]['count'])
    ]


@site.app_template_global()
def es_date(value):
    return datetime.strptime(value, '%Y-%m-%d').strftime('%d/%m/%Y')


@site.route('/')
def home():
    return render_template('index.html', **home_data())


@site.route('/search')
def search():
    return render_template('search.html', **search_reports())


class AlertAnonForm(FlaskForm):
    details = TextField()

    def validate_details(form, field):
        if RE_URL.search(field.data):
            raise ValidationError("Vous ne pouvez pas soumettre d'URL")


@site.route('/<id>/')
def display(id):
    report = Report.objects.get_or_404(id=id)
    return render_template('report.html', report=report, form=AlertAnonForm())


@site.route('/<id>/alert', methods=['POST'])
def alert(id):
    report = Report.objects.get_or_404(id=id)
    form = AlertAnonForm()
    if form.validate_on_submit():
        csvfile = StringIO.StringIO()
        writer = csvcustom.writer(csvfile)
        writer.writerow(csvcustom.ANON_HEADER)
        writer.writerow(csvcustom.to_anon_row(report))
        attachment = Attachment(
            'ccomptes-fix-{0}.csv'.format(report.id),
            'text/csv',
            csvfile.getvalue()
        )
        mail.send_message("Défaut d'anonymisation sur le rapport de la Cour des comptes {0}".format(report.id),
                          recipients=[site.config['ANON_ALERT_MAIL']],
                          html=render_template('anon_alert_mail.html', report=report, details=form.details.data),
                          attachments=[attachment]
                          )
        flash(
            "<strong>Merci pour votre contribution!</strong> Nous avons bien pris en compte votre signalement.",
            'success'
        )
        return redirect(url_for('site.display', id=report.id))
    else:
        abort(400)


@site.route('/robots.txt')
def robots():
    return Response(render_template('robots.txt'), mimetype='text/plain')


@site.route('/sitemap.xml')
def sitemap():
    xml = render_template('sitemap.xml', reports=Report.objects)
    return Response(xml, mimetype='application/xml')


@site.route('/export')
def export_csv():
    def generate():
        csvfile = StringIO.StringIO()
        writer = csvcustom.writer(csvfile)
        # Generate header
        writer.writerow(csvcustom.HEADER)
        yield csvfile.getvalue()

        for report in Report.objects.order_by('id'):
            csvfile = StringIO.StringIO()
            writer = csvcustom.writer(csvfile)
            writer.writerow(csvcustom.to_row(report))
            yield csvfile.getvalue()

    date = datetime.now().date().isoformat()
    headers = {
        b'Content-Disposition': 'attachment; filename=ccomptes-{0}.csv'.format(date),
        # b'X-Accel-Buffering': 'no',
    }
    response = Response(generate(), mimetype="text/csv", headers=headers)
    return response


# @site.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404


def init_app(app):
    app.errorhandler(400)(page_not_found)
    mail.init_app(app)
    app.register_blueprint(site)

ccomptes/templates/anon_alert_mail.html
<p>
Un défaut d'anonymisation a été signalé sur
l'<a href="{{ url_for('site.display', id=report.id, _external=True) }}">rapport Cour des comptes {{report.id}}</a>.
</p>

{% if details %}
<p><b>Informations complémentaires fournies par le lanceur d'alerte:</b></p>
<p><i>{{details}}</i></p>

<p>Le rapport en question est en pièce jointe au format CSV.</p>
{% endif %}

ccomptes/templates/api.html
{% extends "base.html" %}

{% block title %}API{% endblock %}

{% block content %}
<div class="page-header">
  <h1>API <small>Documentation</small></h1>
</div>

<p>L'API de api.ccomptes.fr ne contient que deux points d'entrée :</p>
<ul>
    <li><code>/api/&lt;id&gt;/</code> : pour l'accès direct à un rapport depuis son identifiant</li>
    <li><code>/api/search</code> : pour la recherche paginée</li>
</ul>
<p>Le fonctionnement est strictement similaire à celui des pages web.</p>

<h2>Accès direct</h2>
<p>Cette API permet l'accès direct à un rapport de la Cour des comptes par son identifiant.</p>

<h3>Exemple</h3>
<p>Voici un exemple d'accès direct au rapport n°{{ sample.id }} : </p>
<p><code>GET {{ url_for('api.display', id=sample.id) }}</code></p>
<p><pre data-api="{{ url_for('api.display', id=sample.id) }}"></pre></p>

<h2>Recherche</h2>
<p>La recherche accepte les paramètres d'URL suivants :</p>
<ul>
    <li><code>q</code> : recherche textuelle</li>
    <li>
        <code>sort</code> : critère de tri. Le tri s'effectue sur le score de recherche si ce paramètre n'est pas spécifié. Les valeurs possibles sont:
        <ul>
            <li><code>juridiction (asc|desc)</code> : tri par juridiction</li>
            <li><code>topic (asc|desc)</code> : tri par thème</li>
            <li><code>publication (asc|desc)</code> : tri par date de publication</li>
        </ul>
    </li>
    <li><code>juridiction</code> : filtre sur l'juridiction spécifiée</li>
    <li><code>tag</code> : filtre sur la tag spécifié (peut-être spécifié plusieurs fois)</li>
    <li><code>topic</code> : filtre sur le thème spécifié</li>
    <li><code>publication</code> : filtre sur la publication spécifiée (au format <code>yyyy-mm-dd</code></li>
    <li><code>page</code> : affiche la page indiquée (en relation avec <code>page_size</code>)</li>
    <li><code>page_size</code> : spécifie la taille de la pagination (20 par défaut)</li>
</ul>

<p>La réponse est un objet JSON à 5 attributs :</p>
<ul>
    <li><code>reports</code> : une liste triée des rapports correspondants aux critères de recherche</li>
    <li><code>page</code> : le numéro de la page courante</li>
    <li><code>page_size</code> : la taille de la pagination</li>
    <li><code>total</code> : le nombre total de rapports retournés par la recherche</li>
    <li>
        <code>facets</code> : les différents facettes associées à la recherche sous la forme de liste de triplets :
        <ol>
            <li>la valeur du champ associé à la facette</li>
            <li>le nombre d'occurence dans les résultats de la recherche</li>
            <li><code>true</code> si un filtre est appliqué sur cette valeur</li>
        </ol>
    </li>
</ul>

<h3>Exemple</h3>
<p>Voici un exemple de recherche sur le terme "Paris", triée par dates de publication décroissantes et n'affichant que les 3 premiers éléments :</p>
<p><code>GET {{ url_for('api.search', q='Paris', sort='publication desc', page_size=3) }}</code></p>
<p><pre data-api="{{ url_for('api.search', q='Paris', sort='publication desc', page_size=3) }}"></pre></p>
{% endblock %}


{% block extra_js %}
{% assets "js-api" %}
<script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% endblock %}

ccomptes/templates/base.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Sans titre{% endblock %} - api.ccomptes.fr</title>

    {% assets "css" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
</head>
<body>
    <div class="main-wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        <a href="/">api.ccomptes.fr</a>
                    </div>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('api.doc') }}">Documentation de l'API</a></li>
                    </ul>
                    {# Optionnal search bar #}
                    {% set display_search = display_search|default(True) %}
                    {% if display_search %}
                    <form class="navbar-form navbar-right" role="search"
                        action="{{ url_for('site.search') }}">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Recherche"
                                name="q" value="{{ request.args.q }}">
                        </div>
                        <button type="submit" class="btn btn-default">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </nav>


        <div class="container">
            {% for  category, message in get_flashed_messages(with_categories=true) %}
            <div class="alert alert-{{category|default('info')}} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message|safe }}
            </div>
            {% endfor %}

            <div class="page">
            {% block content %}{% endblock %}
            </div>
        </div>

        {% include "footer.html" %}
    </div>

    {% assets "js" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
    {% endassets %}
    {% block extra_js %}{% endblock %}

    {% include "piwik.html" %}
</body>
</html>

ccomptes/templates/footer.html
<section class="footer">
    <div class="container">
        <footer class="row">

            <section class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                <h5>Ce site</h5>
                <p>Ce site permet de rechercher et d'explorer les rapports publics de la Cour des comptes</p>
            </section>

            <section class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                <h5>Réseau</h5>
                <ul>
                    <li><a href="http://www.ccomptes.fr/">ccomptes.fr</a></li>
                </ul>
            </section>

            <!-- <section class="col-xs-6 col-sm-3 col-md-4 col-lg-4">
                <h5>Contact</h5>
                <ul>
                    <li><a href="https://twitter.com/Etalab">Twitter</a></li>
                    <li><a href="https://github.com/etalab">GitHub</a></li>
                </ul>
            </section> -->

            <!-- <section class="col-xs-9 col-xs-offset-3 col-sm-offset-0 col-sm-2 col-md-2 col-lg-2">
                <a href="http://etalab.gouv.fr/">
                <img class="logo" src="{{ static('img/etalab-logo.png') }}" />
                </a>
                <p>2017 ETALAB</p>
            </section> -->

            <p class="bottom-right"><a href="#">Haut de page</a></p>

        </footer>
    </div>
</section>

ccomptes/templates/index.html
{% extends "base.html" %}
{% set display_search = False %}

{% block title %}Accueil{% endblock %}

{% block content %}
<div class="container-full">
    <div class="row">
        <div class="col-sm-12 text-center v-center">
            <form class="col-sm-12 megasearch" action="{{ url_for('site.search') }}">
                <div class="input-group">
                    <input name="q" class="form-control input-lg"
                        placeholder="Retrouvez un rapport de la Cour des comptes parmi les {{total}} disponibles {% if total %}({{publications.from.strftime('%d/%m/%Y')}} au {{publications.to.strftime('%d/%m/%Y')}}){% endif %}"
                        type="text">
                    <div class="input-group-btn">
                        <button class="btn btn-lg btn-primary" type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <!-- <div class="col-sm-12">
            <h3>Mots-clés</h3>
            <ul class="tags blue">
                {% for tag, count in tag_cloud %}
                    <li>
                        <a href="{{ url_for('site.search', tag=tag) }}">
                            {{ tag }}
                            <span>{{ count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div> -->
        <!-- <div class="col-sm-6">
            <h3>Thèmes</h3>
            <ul class="tags topics">
                {% for topic, count in topics %}
                    <li>
                        <a href="{{ url_for('site.search', topic=topic) }}">
                            {{ topic }}
                            <span>{{ count }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div> -->
    </div>
</div>
{% endblock %}

ccomptes/templates/piwik.html
{% if config.PIWIK_URL and config.PIWIK_ID %}
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://{{ config.PIWIK_URL }}/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "{{ config.PIWIK_ID }}"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
{% endif %}

ccomptes/templates/report.html
{% extends "base.html" %}

{% block title %}{{ report.subject|truncate(100) }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>
            {{ report.subject }}
            <small>Rapport du {{ report.publication.strftime('%d/%m/%Y') }}</small>
        </h1>
        <!-- <div class="lead subject raw">
            {{- report.subject -}}
        </div> -->
        <!-- <div class="content raw"> -->
          <div class = "content">
            {{ report.content|safe }}
          </div>
        <!-- </div> -->
    </div>
    <aside class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-home"></span>
                Juridiction
            </div>
            <div class="panel-body">
                <a href="{{ url_for('site.search', juridiction=report.juridiction) }}">
                    {{ report.juridiction }}
                </a>
            </div>

            <div class="panel-heading">
                <span class="glyphicon glyphicon-book"></span>
                Type de rapport
            </div>
            <div class="panel-body">
                {% for type in report.types %}
                <a href="{{url_for('site.search', type=type) }}" class="label label-primary">{{ type }}</a>
                {% endfor %}
            </div>

            <!-- <div class="panel-heading">
                <span class="glyphicon glyphicon-book"></span>
                Thèmes
            </div>
            <div class="panel-body topics">
                {% for topic, subtopics in report.topics|treeize %}
                    <a href="{{url_for('site.search', topic=topic) }}"
                        class="label label-primary topic">
                        <span class="glyphicon glyphicon-folder-{{'open' if subtopics else 'close'}}"></span>
                        {{ topic }}
                    </a>
                    {% for subtopic in subtopics %}
                    <a class="label label-default subtopic"
                        href="{{ url_for('site.search', topic=topic+'/'+subtopic) }}">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        {{ subtopic }}
                    </a>
                    {% endfor %}
                {% endfor %}
            </div> -->


            <!-- <div class="panel-heading">
                <span class="glyphicon glyphicon-tags"></span>
                Mots-clés
            </div>
            <div class="panel-body">
                {% for tag in report.tags %}
                <a href="{{url_for('site.search', tag=tag) }}" class="label label-primary">{{ tag }}</a>
                {% endfor %}
            </div> -->

            <!-- <a href
                class="btn btn-xs btn-info btn-block"
                title="Signaler un défaut d'anonymisation"
                data-toggle="modal" data-target="#alert-modal">
                Signaler un défaut d'anonymisation
            </a> -->
    </aside>
</div>
{% endblock %}

{% block extra_js %}
{# Anonimization error signalization modal #}
<div class="modal fade" id="alert-modal" tabindex="-1" role="dialog" aria-labelledby="alert-modal-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="alert-modal-label">Signaler un défaut d'anonymisation</h4>
            </div>
            <div class="modal-body">
                <p>
                    Aidez à détecter et corriger les défauts d'anonymisation en les signalant avec ce formulaire.
                </p>
                <form id="alert-form" method="POST"
                    action="{{ url_for('site.alert', id=report.id) }}">
                    {{ form.csrf_token }}
                    <textarea name="details" class="form-control" rows="3"
                        placeholder="Saisissez éventuellement quelques informations complémentaires sur l'erreur"></textarea>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" form="alert-form" class="btn btn-primary">Signaler</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ccomptes/templates/search.html
{% extends "base.html" %}
{% import 'macros.html' as m %}
{% set display_search = False %}

{% set sorters = {
    'topic': ('Thème', 'alphabet'),
    'juridiction': ('Juridiction', 'alphabet'),
    'publication': ('Publication', 'order'),
    'type': ('Type de rapport', 'alphabet'),
} %}

{% block title %}Recherche{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">

        <div class="row">
            <form class="col-lg-12" action="{{ url_for('site.search', **request.args) }}">
                <div class="input-group">
                    <input type="text" name="q" class="form-control"
                        placeholder="Recherche" value="{{ request.args.q }}">
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            {% if in_url('sort') %}
                                {% set sort, order = request.args.sort.split(' ') %}
                                {% set label, type = sorters[sort] %}
                                {% set suffix = '-alt' if order == 'desc' else '' %}
                                <span class="glyphicon glyphicon-sort-by-{{type}}{{suffix}}"></span>
                                {{ label }}
                            {% else %}
                                <span class="glyphicon glyphicon-sort-by-attributes-alt"></span>
                                Pertinence
                            {% endif %}
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right">
                            <li>
                                <a href="{{ url_rewrite(page=1)|url_del('sort') }}">
                                    Pertinence
                                </a>
                            </li>
                            {% for field, (label, type) in sorters.items() %}
                                {{ m.sorter_entries(field, label, type) }}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-sm-12 label-list">
                {{ m.filter_label('juridiction', 'Juridiction', 'home') }}
                {{ m.filter_label('publication', 'Publication', 'calendar', es_date) }}
                {{ m.filter_label('type', 'Type de rapport', 'book') }}
                <!-- {{ m.filter_label('tag', 'Mot-clé', 'tag') }}
                {{ m.filter_label('topic', 'Thème', 'book') }} -->
            </div>
        </div>

        <hr/>

        <ul class="list-unstyled search-result">
            {% for report in reports %}
            <li>
                <a class="title" href="{{ url_for('site.display', id=report.id) }}">
                    {{ report.subject|truncate(100) }}
                </a>
                <div class="subtitle">
                    <span class="glyphicon glyphicon-home"></span>
                    {{ report.juridiction }}
                </div>
                <div class="label-list">
                    <a class="label label-default" title="Publication"
                        href="{{url_for('site.search', publication=report.publication.strftime('%Y-%m-%d')) }}">
                        <span class="glyphicon glyphicon-calendar"></span>
                        {{ report.publication.strftime('%d/%m/%Y') }}
                    </a>
                    {% for type in report.types %}
                    <a class="label label-default" title="Type de rapport"
                        href="{{url_for('site.search', type=type) }}">
                        <span class="glyphicon glyphicon-book"></span>
                        {{ type }}
                    </a>
                    {% endfor %}
                    <!-- {% for topic in report.topics %}
                    <a class="label label-primary" title="Thème"
                        href="{{url_for('site.search', topic=topic) }}">
                        <span class="glyphicon glyphicon-book"></span>
                        {{ topic }}
                    </a>
                    {% endfor %} -->
                    <!-- {% for tag in report.tags %}
                    <a class="label label-default" title="Tag"
                        href="{{url_for('site.search', tag=tag) }}">
                        <span class="glyphicon glyphicon-tag"></span>
                        {{ tag }}
                    </a>
                    {% endfor %} -->
                </div>
            </li>
            {% else %}
            <li>Aucun résultat</li>
            {% endfor %}
        </ul>

        {{ m.paginator(page, page_size, total) }}

    </div>
    <aside class="col-md-4">

        <div class="panel panel-default">
            <div class="panel-heading">
                {% if total %}
                    Résultats {{ ((page - 1) * page_size) + 1 }}
                    à {{ page * page_size if page * page_size <= total else total }}
                    sur {{ total }} trouvés.
                {% else %}
                    Aucun résultat trouvé
                {% endif %}
            </div>
            {{ m.facet_filter(facets, 'juridiction', 'Juridictions', 'home') }}
            {{ m.facet_filter(facets, 'publication', 'Publications', 'calendar', es_date) }}
            {{ m.facet_filter(facets, 'type', 'Type de rapport', 'book') }}
            <!-- {{ m.facet_filter(facets, 'tag', 'Mots-clés', 'tags') }}
            {{ m.tree_facet_filter(facets, 'topic', 'Thèmes', 'book') }} -->
        </div>

    </aside>
</div>

{% endblock %}